### ISSUE TITLE
Z Camera driver and launch 

### ISSUE THREAD

**Issue by AbBaSaMo** [Monash-Connected-Autonomous-Vehicle/ESDA#22]
- [x] Get the Z Camera working and outputting an image via rviz
- [x] Where applicable, get a launch file with any required parameters/configurations implemented so we can launch this using our [overall] sensor kit launch file

Refer to the following repository https://github.com/stereolabs/zed-ros2-wrapper
Refer to the following issue in the AVP project which also deals with setting up the Z Cam https://github.com/Monash-Connected-Autonomous-Vehicle/ENV200-Shadow-Repo/issues/4

**Comment by m076em** [comment]
Z cam setup:
1-Install [CUDA](https://developer.nvidia.com/cuda-downloads)
2-Download corresponding version of Zed [SDK](https://www.stereolabs.com/developers/release#82af3640d775)
3-[Install SDK](https://www.stereolabs.com/docs/installation/linux)

**Comment by AbBaSaMo** [comment]
@m076em since you mentioned the drivers work with no issues, and based on the driver README there doesn't seem to be any modifications to any launch/config files, I'll close this issue.

**Comment by AbBaSaMo** [comment]
@m076em would you happen to know the model of the zcam?


![Image](https://github.com/Monash-Connected-Autonomous-Vehicle/ESDA/assets/95030427/5b8598c8-0d98-433e-a741-b15c946cf17a)

**Comment by AbBaSaMo** [comment]
Experienced the following error from zed pkgs while trying to build:

<img src="https://github.com/Monash-Connected-Autonomous-Vehicle/ESDA/assets/95030427/85f97286-8e22-4ca9-ad68-9f22ee8a393c" width="400"/>

Tried installing `sudo apt-get install libjpeg-turbo8-dev libturbojpeg` which solved the issue though it's odd that I did not experience it before

![Image](https://github.com/Monash-Connected-Autonomous-Vehicle/ESDA/assets/95030427/7ba3f4ae-fb4c-4b69-b360-56793474ba54)

**Comment by m076em** [comment]
I haven't seen this error either, it might do with a incompatible version of the sdk driver, but I am not sure

**Comment by AbBaSaMo** [comment]
@Jokua @AbBaSaMo update stack so it uses the zed2i

**Comment by AbBaSaMo** [comment]
updated launch arg to zed2i
