### ISSUE TITLE
Create IGVC course map file

### ISSUE THREAD

**Issue by AbBaSaMo** [Monash-Connected-Autonomous-Vehicle/ESDA#3]
Create a model of the IGVC course including mock obstacles and ramp.

**Comment by AbBaSaMo** [comment]
@AnthonyZhOon just confirming that you decided to take this one?

**Comment by AbBaSaMo** [comment]
@AnthonyZhOon we can reuse this fork of ours and the racecourse in it https://github.com/Monash-Connected-Autonomous-Vehicle/minidrone_linorobot/tree/foxy

launch https://github.com/Monash-Connected-Autonomous-Vehicle/minidrone_linorobot/blob/foxy/linorobot2_gazebo/launch/minidrone_sim.launch.py

the map it uses https://github.com/Monash-Connected-Autonomous-Vehicle/minidrone_linorobot/blob/foxy/linorobot2_gazebo/worlds/map1.txt

would just need to add potholes and the ramp iirc and to use humble instead of the foxy branch from the source repo if it has one

**Comment by AnthonyZhOon** [comment]
The linorobot map is usable, we can try disabling physics of the ground plane to see if it works better.
