### ISSUE TITLE
Install key dependencies on Hive5

### ISSUE THREAD

**Issue by AbBaSaMo** [Monash-Connected-Autonomous-Vehicle/ESDA#50]
- [x] piksi deps
- [x] ZCAM deps
- [ ] misc sudo packages
- [ ] install and build the current esda stack

**Comment by AbBaSaMo** [comment]
VCS was not working. A file it tries to use requires root access. 

![Image](https://github.com/Monash-Connected-Autonomous-Vehicle/ESDA/assets/95030427/76f2da59-0beb-493b-b915-a980a4d173bd)

Used sudo with vcs then changed permissions of installed repos to user. @dylan-gonzalez @jaimasters what would be a better approach to solving this for future reference? Cause Ben was talking about the ills of slapping sudo on everything the other day. Idk if changing owner/group for /usr/local/lib/python3.10 onwards is appropriate so I avoided it.

**Comment by dylan-gonzalez** [comment]
I didn't have that issue when I was installing ZED im pretty sure so idk

**Comment by AbBaSaMo** [comment]
@dylan-gonzalez was speaking with Ben who was explaining that the issue was a result of running some installers with sudo and his suggested fix was chmodding necessary files to o=r-x

**Comment by AbBaSaMo** [comment]
for personal ref: running `sudo chmod -R o=r-x /usr/local/lib/python3.10` has fixed it, it seems...

now onto the next issue
![image](https://github.com/Monash-Connected-Autonomous-Vehicle/ESDA/assets/95030427/73322c55-0064-4a63-9135-60972f2850a8)

as per [this](https://community.stereolabs.com/t/build-failure-of-zed-ros2-wrapper-with-sdk-version-4-1/4997), the problem is that the latest version of zed sdk is not compatible with the ros2 wrapper. 

Going to try updating the fork so that new commits would hopefully fix it, otherwise, using a different version of the sdk that is compatible

**Comment by AbBaSaMo** [comment]
Updating the fork seems to have fixed that. And now I have to deal with this
![image](https://github.com/Monash-Connected-Autonomous-Vehicle/ESDA/assets/95030427/e1f9d563-eb59-4129-90ab-7e9d0bc56324)

The issue is with the missing submodule. Deleted the empty directory on esda branch on our fork and now have no idea how to bring it back.

![image](https://github.com/Monash-Connected-Autonomous-Vehicle/ESDA/assets/95030427/5c8901c2-065a-4da5-9747-e9defdb7037e)
![image](https://github.com/Monash-Connected-Autonomous-Vehicle/ESDA/assets/95030427/77dd3d70-2757-48de-ba8b-5281804a6004)

**Comment by AbBaSaMo** [comment]
ok, done, the command was `git submodule add <zed_interface repo url> ./zed-ros2-interfaces`

**Comment by AbBaSaMo** [comment]
yay it worked! closing issue for now
